const fs = require('fs');
const { Database } = require('nyhtron')
const db = new Database('food.json')

let dataX = fs.readFileSync('input.txt', 'utf8');
let data = dataX.replaceAll("'", " ");
console.log(data);
let countries = [
    "ABD Virgin Adaları",
    "Afganistan",
    "Aland Adaları",
    "Almanya",
    "amerika",
    "Amerikan Samoası",
    "Angola",
    "Anguilla",
    "Antarktika",
    "Antigua ve Barbuda",
    "Arjantin",
    "Arnavutluk",
    "Aruba",
    "Avustralya",
    "Avusturya",
    "Azerbaycan",
    "Bahama Adaları",
    "Bahreyn",
    "Bangladeş",
    "Barbados",
    "Belçika",
    "Belize",
    "Belize",
    "Benin",
    "Bermuda",
    "Beyaz Rusya",
    "Bhutan",
    "Birleşik Arap Emirlikleri",
    "Birleşik Krallık",
    "Bolivya",
    "Bosna-Hersek",
    "Botsvana",
    "Bouvet Adası",
    "Brezilya",
    "Brunei",
    "Bulgaristan",
    "Burkina Faso",
    "Burundi",
    "Cape Verde",
    "Cayman Adaları",
    "Cebelitarık",
    "Cezayir",
    "Christmas Adası",
    "Cibuti",
    "Cile",
    "Cincin",
    "Ciprus",
    "Ciribati",
    "Cok-Küba",
    "Cok-Küba (Kanarya Adaları)",
    "Cook Adaları",
    "Avustralya",
    "Doğu",
    "Türkiye",
    "İskoç",
    "Costa Rica",
    "Cuba",
    "Curaçao",
    "Cezayir",
    "Danimarka",
    "Doğu Afrika",
    "Dominik",
    "Dominika",
    "Ekvador",
    "Ekvator",
    "Ekvator Ginesi",
    "El Salvador",
    "Endonezya",
    "Eritre",
    "Ermenistan",
    "Estonya",
    "Etiyopya",
    "Falkland Adaları",
    "Faroe Adaları",
    "Fas",
    "Fiji",
    "Fildişi Sahili",
    "Filipinler",
    "Finlandiya",
    "Folkland Adaları",
    "Fransa",
    "Fransız Guyanası",
    "Fransız Güney Eyaletleri",
    "Fransız Polinezyası",
    "Fransızca Guyanası",
    "Fransızca Güney Eyaletleri",
    "Fransızca Polinezyası",
    "Gabon",
    "Gambiya",
    "Gana",
    "Gine",
    "Gine-Bissau",
    "Grenada",
    "Grenadya",
    "Grönland",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guineya",
    "Guyana",
    "Güney Afrika",
    "Güney Georgia ve Güney Sandwich Adaları",
    "Güney Kıbrıs Rum Yönetimi",
    "Güney Kore",
    "Güney Kore",
    "Güney Sudan",
    "Gürcistan",
    "Haiti",
    "Hırvatistan",
    "Hindistan",
    "Hollanda",
    "Hollanda Antilleri",
    "Hollanda Kıbrıs Rum Yönetimi",
    "Honduras",
    "Hong Kong",
    "Hırvatistan",
    "Irak",
    "İngiltere",
    "İran",
    "İrlanda",
    "İspanya",
    "İsrail",
    "İsveç",
    "İsviçre",
    "İtalya",
    "İzlanda",
    "Jamaika",
    "Japonya",
    "Johnston Atoll",
    "K.K.T.C.",
    "Kamboçya",
    "Kamerun",
    "Kanada",
    "Kanarya Adaları",
    "Karadağ",
    "Katar",
    "Kazakistan",
    "Kenya",
    "Kıbrıs Rum Yönetimi",
    "Kırgızistan",
    "Kiribati",
    "Kolombiya",
    "Komorlar",
    "Kongo",
    "Kongo",
    "Kongo",
    "Kosova",
    "Kosta Rika",
    "Kuveyt",
    "Kuzey İrlanda",
    "Kuzey Kore",
    "Kuzey Maryana Adaları",
    "Küba",
    "Laos",
    "Lesotho",
    "Letonya",
    "Liberya",
    "Libya",
    "Liechtenstein",
    "Litvanya",
    "Lübnan",
    "Lüksemburg",
    "Macaristan",
    "Madagaskar",
    "Makau",
    "Makedonya",
    "Malavi",
    "Maldiv Adaları",
    "Malezya",
    "Mali",
    "Malta",
    "Marşal Adaları",
    "Martinik",
    "Mauritius",
    "Mayotte",
    "Meksika",
    "Mısır",
    "Midway Adaları",
    "Mikronezya",
    "Mısır",
    "Moğolistan",
    "Moldavya",
    "Monako",
    "Montserrat",
    "Moritanya",
    "Mozambik",
    "Namibia",
    "Nauru",
    "Nepal",
    "Nijer",
    "Nijerya",
    "Nikaragua",
    "Niue",
    "Norveç",
    "Orta Afrika",
    "Özbekistan",
    "Pakistan",
    "Palau Adaları",
    "Palmyra Atoll",
    "Panama",
    "Papua Yeni Gine",
    "Paraguay",
    "Peru",
    "Polonya",
    "Portekiz",
    "Porto Riko",
    "Reunion",
    "Romanya",
    "Ruanda",
    "Rusya",
    "Saint Helena",
    "Saint Martin",
    "Saint Pierre ve Miquelon",
    "Samoa",
    "San Marino",
    "Santa Kitts ve Nevis",
    "Santa Lucia",
    "Santa Vincent ve Grenadinler",
    "Sao Tome ve Principe",
    "Senegal",
    "Seyşeller",
    "Sırbistan",
    "Sierra Leone",
    "Singapur",
    "Slovakya",
    "Slovenya",
    "Lüksemburg",
    "Solomon Adaları",
    "Somali",
    "Sri Lanka",
    "Sudan",
    "Surinam",
    "Suriye",
    "Suudi Arabistan",
    "Svalbard ve Jan Mayen Adaları",
    "Svaziland",
    "Şili",
    "Şimali Mariana Adaları",
    "Tacikistan",
    "Tanzanya",
    "Tayland",
    "Tayvan",
    "Togo",
    "Tonga",
    "Trinidad ve Tobago",
    "Tunus",
    "Türkmenistan",
    "Turks ve Caicos Adaları",
    "Tuvalu",
    "Uganda",
    "Ukrayna",
    "Umman",
    "Uruguay",
    "Ürdün",
    "Vallis ve Futuna Adaları",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Virgin Adaları",
    "Virgin Adaları",
    "Virgin Adaları (Britanya)",
    "Virgin Adaları (İngiltere)",
    "Wake Adaları",
    "Yemen",
    "Yeni Kaledonya",
    "Yeni Zelanda",
    "Yunanistan",
    "Zambiya",
    "Zimbabve"
]

    var words = data.split(/\s+/);
    let tempCA = countries.map(name => name.toLowerCase());
    
    console.log(words)
    words.forEach(function(word) {
        console.log("hello")
        tempW = word.toLowerCase()
        if(tempCA.includes(tempW)){
            db.add(tempW, 1)
        }
        

    });